export const FLUENT_ICON_NAMES = [
  'home',
  'arrowDownload',
  'github',
  'navigation',
  'arrowLeft',
  'bookOpen',
  'mail',
  'qq',
  'chat',
  'chevronDown',
  'checkmarkCircle',
  'warning',
  'dismissCircle',
  'dismiss',
  'info',
  'box',
  'documentCopy',
  'video',
  'questionCircle',
  'windows',
  'linux',
  'macos',
  'settings',
  'arrowClockwise',
  'archive',
  'personVoice',
  'briefcase',
  'clock',
  'documentEdit',
  'arrowUpload',
  'peopleCommunity',
  'layer',
  'lockClosed',
  'tagMultiple',
  'speaker2',
  'speakerMute',
  'codeText'
] as const;

export type FluentIconName = (typeof FLUENT_ICON_NAMES)[number];
