/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTopBar: typeof import('./components/AppTopBar.vue')['default']
    DownloadDialog: typeof import('./components/DownloadDialog.vue')['default']
    DownloadPlatformCard: typeof import('./components/DownloadPlatformCard.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    PluginCard: typeof import('./components/PluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitDownloadButton: typeof import('./components/SplitDownloadButton.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
