/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppTopBar: typeof import('./components/AppTopBar.vue')['default']
    DownloadDialog: typeof import('./components/DownloadDialog.vue')['default']
    DownloadPlatformCard: typeof import('./components/DownloadPlatformCard.vue')['default']
    FeatureCard: typeof import('./components/FeatureCard.vue')['default']
    FluentButton: typeof import('./components/fluent/FluentButton.vue')['default']
    FluentCard: typeof import('./components/fluent/FluentCard.vue')['default']
    FluentCheckbox: typeof import('./components/fluent/FluentCheckbox.vue')['default']
    FluentComboBox: typeof import('./components/fluent/FluentComboBox.vue')['default']
    FluentDialog: typeof import('./components/fluent/FluentDialog.vue')['default']
    FluentExpander: typeof import('./components/fluent/FluentExpander.vue')['default']
    FluentFlipView: typeof import('./components/fluent/FluentFlipView.vue')['default']
    FluentInfoBar: typeof import('./components/fluent/FluentInfoBar.vue')['default']
    FluentProgressRing: typeof import('./components/fluent/FluentProgressRing.vue')['default']
    FluentSegmentedControl: typeof import('./components/fluent/FluentSegmentedControl.vue')['default']
    FluentSelectorBar: typeof import('./components/fluent/FluentSelectorBar.vue')['default']
    FluentSideNav: typeof import('./components/fluent/FluentSideNav.vue')['default']
    FluentSlider: typeof import('./components/fluent/FluentSlider.vue')['default']
    FluentSnackbar: typeof import('./components/fluent/FluentSnackbar.vue')['default']
    FluentSplitButton: typeof import('./components/fluent/FluentSplitButton.vue')['default']
    FluentSystemIcon: typeof import('./components/FluentSystemIcon.vue')['default']
    FluentTextBox: typeof import('./components/fluent/FluentTextBox.vue')['default']
    FluentToggleSwitch: typeof import('./components/fluent/FluentToggleSwitch.vue')['default']
    PluginCard: typeof import('./components/PluginCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplitDownloadButton: typeof import('./components/SplitDownloadButton.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon.vue')['default']
  }
}
