/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[..path]': RouteRecordInfo<'/[..path]', '/:ath(.*)', { ath: ParamValue<true> }, { ath: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/download/': RouteRecordInfo<'/download/', '/download', Record<never, never>, Record<never, never>>,
    '/download/thank_you/[indexId]/[version]/[appSubChannel]/': RouteRecordInfo<'/download/thank_you/[indexId]/[version]/[appSubChannel]/', '/download/thank_you/:indexId/:version/:appSubChannel', { indexId: ParamValue<true>, version: ParamValue<true>, appSubChannel: ParamValue<true> }, { indexId: ParamValue<false>, version: ParamValue<false>, appSubChannel: ParamValue<false> }>,
    '/download/thank_you/v2/[version]/[appSubChannel]/': RouteRecordInfo<'/download/thank_you/v2/[version]/[appSubChannel]/', '/download/thank_you/v2/:version/:appSubChannel', { version: ParamValue<true>, appSubChannel: ParamValue<true> }, { version: ParamValue<false>, appSubChannel: ParamValue<false> }>,
    '/download/v1/': RouteRecordInfo<'/download/v1/', '/download/v1', Record<never, never>, Record<never, never>>,
    '/download/v2/': RouteRecordInfo<'/download/v2/', '/download/v2', Record<never, never>, Record<never, never>>,
  }
}
